# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.7"
    
sphinx:
   configuration: doc/source/conf.py

python:
  #Install our python package before building the docs
  install:
    - requirements: requirements.txt  
    
sphinx:
  fail_on_warning: true
